#ifndef PNGOPTIM_FFI_H
#define PNGOPTIM_FFI_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Input options for PNG optimization.
 */
typedef struct PNGOptimOptions {
  /**
   * Whether a quality constraint is set.
   */
  bool has_quality;
  /**
   * Minimum acceptable quality (0-100).
   */
  uint8_t quality_min;
  /**
   * Maximum (target) quality (0-100).
   */
  uint8_t quality_max;
  /**
   * Speed preset (1-11, 0 = default of 4).
   */
  uint8_t speed;
  /**
   * Dither level (0.0-1.0, negative = default of 1.0).
   */
  float dither_level;
  /**
   * Posterize bits (0 = disabled).
   */
  uint8_t posterize;
  /**
   * Strip metadata from output.
   */
  bool strip;
  /**
   * Skip output if it would be larger than input.
   */
  bool skip_if_larger;
  /**
   * Skip ICC profile color-space normalization.
   */
  bool no_icc;
} PNGOptimOptions;

/**
 * Result of PNG optimization.
 */
typedef struct PNGOptimResult {
  /**
   * Output PNG data (owned by this struct).
   */
  uint8_t *data;
  /**
   * Length of data in bytes.
   */
  uintptr_t data_len;
  /**
   * Image width in pixels.
   */
  uint32_t width;
  /**
   * Image height in pixels.
   */
  uint32_t height;
  /**
   * Input file size in bytes.
   */
  uint64_t input_bytes;
  /**
   * Output file size in bytes.
   */
  uint64_t output_bytes;
  /**
   * Quality score (0-100).
   */
  uint8_t quality_score;
  /**
   * Quality MSE (mean squared error).
   */
  double quality_mse;
  /**
   * Decode time in milliseconds.
   */
  double decode_ms;
  /**
   * Quantize time in milliseconds.
   */
  double quantize_ms;
  /**
   * Encode time in milliseconds.
   */
  double encode_ms;
  /**
   * Total processing time in milliseconds.
   */
  double total_ms;
  /**
   * Error code (0 = success).
   */
  int32_t error_code;
  /**
   * Error message (null on success, owned CString on error).
   */
  char *error_message;
  /**
   * For QualityTooLow: the minimum quality that was required.
   */
  uint8_t quality_minimum;
  /**
   * For SkipIfLargerRejected: the maximum file size threshold.
   */
  uint64_t maximum_file_size;
} PNGOptimResult;

/**
 * Returns default optimization options.
 */
struct PNGOptimOptions pngoptim_default_options(void);

/**
 * Process PNG data with the given options.
 *
 * Returns a heap-allocated `PNGOptimResult` that must be freed with
 * `pngoptim_result_free`. Returns null only if `input` is null.
 */
struct PNGOptimResult *pngoptim_process(const uint8_t *input,
                                        uintptr_t input_len,
                                        const struct PNGOptimOptions *options);

/**
 * Free a result previously returned by `pngoptim_process`.
 */
void pngoptim_result_free(struct PNGOptimResult *result);

#endif  /* PNGOPTIM_FFI_H */
